// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Animation",
                            Price = 24.99m,
                            ReleaseDate = new DateOnly(1999, 11, 13),
                            Title = "Toy Story 2"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Science Fiction",
                            Price = 19.99m,
                            ReleaseDate = new DateOnly(1999, 3, 31),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action",
                            Price = 29.99m,
                            ReleaseDate = new DateOnly(2010, 7, 16),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Drama",
                            Price = 14.99m,
                            ReleaseDate = new DateOnly(1994, 9, 23),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Crime",
                            Price = 18.99m,
                            ReleaseDate = new DateOnly(1994, 10, 14),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Action",
                            Price = 24.99m,
                            ReleaseDate = new DateOnly(2008, 7, 18),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Drama",
                            Price = 17.99m,
                            ReleaseDate = new DateOnly(1994, 7, 6),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Animation",
                            Price = 19.99m,
                            ReleaseDate = new DateOnly(1994, 6, 24),
                            Title = "The Lion King"
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Action",
                            Price = 21.99m,
                            ReleaseDate = new DateOnly(2000, 5, 5),
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Romance",
                            Price = 22.99m,
                            ReleaseDate = new DateOnly(1997, 12, 19),
                            Title = "Titanic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
